# Generated by Django 4.2.16 on 2024-09-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendCode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
