# Generated by Django 4.2.16 on 2024-09-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendCode', '0002_remove_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=150, null=True)),
                ('color', models.CharField(max_length=50)),
                ('blooming_season', models.CharField(max_length=50)),
                ('petal_count', models.IntegerField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flower_images/')),
                ('care_instructions', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
