# Generated by Django 4.2.16 on 2024-09-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendCode', '0003_flower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='client_images/'),
        ),
    ]
