# Generated by Django 4.2.16 on 2024-12-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendCode', '0006_alter_client_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flower',
            table='BackendCode_flower',
        ),
    ]
