# Generated by Django 4.2.16 on 2024-12-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendCode', '0009_category_flower_categoryid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='BackendCode_category',
        ),
    ]
